spring:
  application:
    name: user-management-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  flyway:
    enabled: true
    locations: classpath:db/migration
  session:
    timeout: 60
server:
  port: 8080
